made validate-pr only a build w/optional artifact. finalize-pr does the rest if artifact found. approve-fork-pr builds artifact for fork if approved by owner. TODO - dedup approve-fork-pr and validate-pr, differ pr comments for fork

diff --git a/.github/workflows/finalize-pr.yml b/.github/workflows/finalize-pr.yml
--- a/.github/workflows/finalize-pr.yml
+++ b/.github/workflows/finalize-pr.yml
@@ -4,21 +4,65 @@ on:
   workflow_run:
     workflows:
       - 'validate pr'
+      - 'approve fork pr'
     types:
       - completed
+
+permissions:
+  contents: read
+  pull-requests: write
+  pages: write
+  id-token: write
 
 defaults:
   run:
     shell: bash
 
+ env:
+  PR_NUM: ${{ github.event.pull_request.number }}
+  RUN_NUM: ${{ github.run_number }}
+
 jobs:
 
-  build:
+  preconditions:
+    needs: debugging
     if: |
-      github.event.workflow_run.event == 'pull_request' &&
-      github.event.workflow_run.conclusion == 'success'
+       (github.event.pull_request.head.repo.fork == false &&
+        startsWith(github.head_ref,'dependabot/submodules/public-') == false) ||
+       (github.event.pull_request.head.repo.fork == true &&
+        github.event_name == 'pull_request_review' &&
+        github.event.review.state == 'approved' &&
+        github.actor == 'wahlax-llc')
+    runs-on: ubuntu-22.04
+    outputs:
+      artifact-found: ${{ steps.verify-gh-pages-artifact.artifact-found }}
+    steps:
+      - name: Precondition passed output
+        run: |
+          echo "Preconditions passed"
+
+      - uses: actions/download-artifact@v3
+        with:
+          name: github-pages
+
+      - name: Verify gh-pages artifact
+        id: verify-gh-pages-artifact
+        run: |
+          if [ -f artifact.tar ]; then
+            echo "found gh-pages artifact"
+            echo "artifact-found=true" >> ${GITHUB_OUTPUT}
+          else
+            echo "missing gh-pages artifact"
+            echo "artifact-found=false" >> ${GITHUB_OUTPUT}
+          fi
+    
+  build:
+    needs: preconditions
+    if: needs.preconditions.outputs.artifact-found != 'true'
     runs-on: ubuntu-22.04
     environment: staging
+    outputs:
+      static-site-sha: ${{ steps.save-static-site.outputs.commit-sha }}
     steps:
 
       - name: Checkout project with submodules
@@ -32,10 +76,135 @@ jobs:
         with:
           name: github-pages
 
-      - name: list files
+      - name: Setup public submodule to capture changes in github-pages
+        id: public-submodule-setup
         run: |
-          echo "PR is ${PR_NUM}"
-          echo "RUN is ${RUN_NUM}"
-          ls
           git status
+          if [ ! -f artifact.tar ]; then
+            echo "missing gh-pages artifact"
+            exit 1
+          fi
+          cd public
+          git checkout main
+          echo "main-sha=$(git rev-parse HEAD)" >> ${GITHUB_OUTPUT}
+          git branch deploy/hugo-pr-${PR_NUM}-${RUN_NUM}
+          git checkout deploy/hugo-pr-${PR_NUM} 2>/dev/null || git checkout -b deploy/hugo-pr-${PR_NUM}
+          echo "pr-sha=$(git rev-parse HEAD)" >> ${GITHUB_OUTPUT}
+          cd ..
+          rm -rf public/*
+          cd public
+          tar -xf ../artifact.tar
+  
+      - name: Preview changes to public submodule
+        id: preview-public-changes
+        run: |
+          cd public
+          git add .
+          git status
+          echo "diff-count=$(git status --porcelain | wc -l)" >> ${GITHUB_OUTPUT}
+          echo "main-diff-count=$(git diff --name-only main | wc -l)" >> ${GITHUB_OUTPUT}
+
+      - name: Save static site for future PR merge
+        id: save-static-site
+        if: |
+          steps.preview-public-changes.outputs.diff-count != '0' &&
+          steps.preview-public-changes.outputs.main-diff-count != '0'
+        run: |
+          cd public
+          git config user.name 'github-actions[bot]'
+          git config user.email 'github-actions[bot]@users.noreply.github.com'
+          git commit -m "generated static site in pr ${PR_NUM} on lexical-cloud-docs-hugo"
+          git checkout deploy/hugo-pr-${PR_NUM}-${RUN_NUM}
+          git merge --squash deploy/hugo-pr-${PR_NUM}
+          git commit -m "generated static site in pr ${PR_NUM} on lexical-cloud-docs-hugo"
+          git push origin --force deploy/hugo-pr-${PR_NUM}-${RUN_NUM}:deploy/hugo-pr-${PR_NUM}
+          echo "commit-sha=$(git rev-parse HEAD)" >> ${GITHUB_OUTPUT}
+
+      - name: Delete static site branch for pr if created and static site is now unchanged
+        if: |
+          steps.preview-public-changes.outputs.main-diff-count == '0' &&
+          steps.public-submodule-setup.outputs.main-sha != steps.public-submodule-setup.outputs.pr-sha
+        run: |
+          cd public
+          git push origin :deploy/hugo-pr-${PR_NUM}
+
+  deploy-prep:
+    needs: build
+    if: needs.build.outputs.static-site-sha != ''
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Checkout project with submodules
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+          submodules: true
+          token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Checkout static site for preview
+        id: checkout-static-site
+        run: |
+          cd public
+          echo "head-commit-sha=$(git rev-parse HEAD)" >> ${GITHUB_OUTPUT}
+          git checkout deploy/hugo-pr-${PR_NUM}
+          echo "branch-commit-sha=$(git rev-parse HEAD)" >> ${GITHUB_OUTPUT}
+        env:
+          PR_NUM: ${{ github.event.pull_request.number }}
+          RUN_NUM: ${{ github.run_number }}
+
+      - name: Exit if static site changed since creation
+        if: |
+          needs.build.outputs.static-site-sha != steps.checkout-static-site.outputs.branch-commit-sha
+        run: |
+          echo "mismatch: ${{needs.build.outputs.static-site-sha}} != ${{steps.checkout-static-site.outputs.branch-commit-sha}}"
           exit 1
+
+      - name: Stage static site for preview
+        run: |
+          touch public/.nojekyll
+          echo 'staging.lexical.cloud' > public/CNAME
+
+      - name: Setup Pages
+        id: pages
+        uses: actions/configure-pages@v3
+
+      - name: Upload artifact
+        uses: actions/upload-pages-artifact@v1
+        with:
+          path: ./public
+
+  deploy:
+    needs: deploy-prep
+    environment:
+      name: github-pages
+      url: ${{ steps.deployment.outputs.page_url }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Deploy to GitHub Pages
+        id: deployment
+        uses: actions/deploy-pages@v2
+
+  comment-on-pr:
+    needs: deploy-prep
+    runs-on: ubuntu-22.04
+    steps:
+      - uses: actions/github-script@v6
+        env:
+          PR_NUM: ${{ github.event.pull_request.number }}
+          RUN_NUM: ${{ github.run_number }}
+        with:
+          script: |
+            const { PR_NUM, RUN_NUM } = process.env
+            github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: `
+            ### Deploy awaiting approval (${RUN_NUM}) for https://staging.lexical.cloud.
+
+            Take these actions before merging:
+              - [ ] Approve the deployment to staging.
+              - [ ] Wait for the deployment to complete after approval.
+              - [ ] Review deployment at https://staging.lexical.cloud.
+              - [ ] Create pr for deploy/hugo-pr-${PR_NUM} on lexical-cloud.github.io repo.
+              - [ ] Update public submodule commit to match deploy/hugo-pr-${PR_NUM} branch.`
+            })
